### ISSUE TITLE
May I suggest using Github's releases  for ebook files 

### ISSUE THREAD

**Issue by eshellman** [SystemsApproach/book#10]
advantages
- no filesize limit, repo and ebook files are easier to download
- syncs the files to a git tag
- associates a tag (version number) with the released files

**Comment by llpeterson** [comment]
It's likely that there's something I don't understand about git, but I thought I was doing that... Release `v5.1` has a corresponding `book.epub` in the `published` directory. What am I missing?

**Comment by llpeterson** [comment]
I don't see how I can associate assets with a release using `git` (as opposed to the `GitHub` api), so I'll need to change my workflow. I'll look into do that next time. Thanks for the suggestion.

**Comment by llpeterson** [comment]
Finally fixed this...
