### ISSUE TITLE
Problem with wording in sentence in 1.1

### ISSUE THREAD

**Issue by RyanGann** [SystemsApproach/book#14]
In section 1.1 Applications, the second to last paragraph contains this sentence:

"Later in the book we will develop a more complete taxonomy of application types to help guide our discussion of key design decisions as we seek to build, operate, and use networks that such a wide range of applications."

The last part of the sentence does not make sense, I'm not sure what it's meant to say.

**Comment by llpeterson** [comment]
Thanks. I suspect the word "support" got dropped at some point, but I fixed by pruning that last clause ("that such..."). The web site will update over night.
