### ISSUE TITLE
Link in 1.1 Application points to a "Page not found" page. 

### ISSUE THREAD

**Issue by yth** [SystemsApproach/book#16]
Under Classes of Applications, the example link (http://www.cs.princeton.edu/llp/index.html) does not go to one of the author's pages. A "Page not found" page from Princeton's website is returned instead.

**Comment by llpeterson** [comment]
Good point. We hadn't originally meant the example URLs to be live, but now that they are, they should be correct. Fixed... the online version will update overnight. (FYI, it should be .../~llp/...)

Larry
