### ISSUE TITLE
Error with sphinx and docutils building the book

### ISSUE THREAD

**Issue by workswiththeweb** [SystemsApproach/book#26]
It appears sphinx and docutils have an incompatibility at the moment. Solution was found here:

https://github.com/readthedocs/readthedocs.org/issues/8616#issuecomment-952034858

I installed docutils 0.18b1 and this resolved my issue. 

make epub
source ./doc_venv/bin/activate ;\
set -u ;\
sphinx-build -M epub "." "_build"  
Running Sphinx v1.8.5
making output directory...
building [mo]: targets for 0 po files that are out of date
building [epub]: targets for 76 source files that are out of date
updating environment: 76 added, 0 changed, 0 removed
reading sources... [  3%] applications/infrastructure                                                                                                                                                              
Exception occurred:
  File "~/systemsapproach/book/doc_venv/lib/python3.8/site-packages/sphinx/domains/std.py", line 638, in note_labels
    n = node.traverse(addnodes.toctree)[0]
TypeError: 'generator' object is not subscriptable
The full traceback has been saved in /tmp/sphinx-err-lr1it0br.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:53: epub] Error 2

(Thanks Jeremy for the assist in figuring this out!)

**Comment by drbruced12** [comment]
With the latest update (commit 194f5c7b25) we have pinned the docutils version to 0.17.1. That seems to be working. Can you confirm it works for you?

**Comment by drbruced12** [comment]
It looks like everything is fixed at this point so closing this issue.
