### ISSUE TITLE
Errors while building the code in Section 1.4 

### ISSUE THREAD

**Issue by sunyiwei24601** [SystemsApproach/book#36]
Hi, I just start to read this book. When it comes to section 1.4 Software, the author provides two example code snippets for socket server and client. They are written in C and don't work  unless I add another 3 lines:
```c
#include <stdlib.h> // for exit
#include <unistd.h> // for close
#include <string.h> // for strlen
```
I am a novice in C Programming so I don't know whether it's my problem or the author just neglect these 3 libraries. If the latter is the real reason, it seems a little bit confused for a beginner.

BTW, I know this book is more about architecture & system approach in theory and I really like them. However, maybe a guide to run the codes mentioned above is also useful, such as:
```bash
gcc server.c -o server.out
./server.out
```
and 
```bash
gcc client.c -o client.out
./client.out localhost
```

**Comment by llpeterson** [comment]
Thanks for your feedback. I'm not surprised the code snippets no longer compile. I'm pretty sure they pre-date C99 (let alone C11), so it's a wonder adding a couple missing include files was enough to fix it.

It would be great to include a link to working code. If you send along a tar/zip file with the working .c files, along with a brief README describing how to use them (including what system(s) you tested it on), we could link the book to it. That would be a welcome contribution!

**Comment by Takashiidobe** [comment]
Would you accept a diff to the C code in the `.rst` files, for example, for the code in section 1.4, along with a note of what systems it compiles on? I tried compiling the code on Linux (Ubuntu 20.04) and Mac (10.15) and it doesn't compile on either unless the following header files are added.

Since stdlib.h, unistd.h, and string.h are part of POSIX, they should be on most Unix-like systems -- the code uses other POSIX headers like sys/socket.h, netinet/in.h, netdb.h, so I don't see why some headers should be omitted but others kept.

Example diff follows:

```diff
diff --git a/foundation/software.rst b/foundation/software.rst
index a3e7ac4..1379c11 100644
--- a/foundation/software.rst
+++ b/foundation/software.rst
@@ -235,6 +235,9 @@ sends it over the socket.
    #include <sys/socket.h>
    #include <netinet/in.h>
    #include <netdb.h>
+   #include <stdlib.h>
+   #include <unistd.h>
+   #include <string.h>
 
    #define SERVER_PORT 5432
    #define MAX_LINE 256
@@ -310,6 +313,9 @@ out the characters that arrive on the connection.
    #include <sys/socket.h>
    #include <netinet/in.h>
    #include <netdb.h>
+   #include <stdlib.h>
+   #include <unistd.h>
+   #include <string.h>
 
    #define SERVER_PORT  5432
    #define MAX_PENDING  5
@@ -339,7 +345,7 @@ out the characters that arrive on the connection.
        exit(1);
      }
      listen(s, MAX_PENDING);
-     
+
     /* wait for connection, then receive and print text */
      while(1) {
        if ((new_s = accept(s, (struct sockaddr *)&sin, &addr_len)) < 0) {
```

**Comment by llpeterson** [comment]
Thanks. I'll add those include files. --Larry
