### ISSUE TITLE
does this project target python 2 only?

### ISSUE THREAD

**Issue by vise890** [SystemsApproach/book#47]
Hi there,

first of all, I am thoroughly enjoying the book. Absolutely great work guys!

I'll get straight to the point: Is this project supposed to work with `python` 3? because it doesn't on my machine (detailed explanation below). However it works with a `python2`-based virtualenv

Now, if the project it's a python 2 only project, would you be open to:
- adding a note in the README, in the [Build the Book section](https://github.com/SystemsApproach/book#build-the-book)?
- maybe even better, force the `Makefile` to create a `python2`-based virtualenv, even on machines that have `python` at version 3.
 
I can create a draft PR if you are interested.
 
### Explanation of breakage under `python` 3

I cloned the repo and ran:
```sh
# this is outside the virtualenv
# it is, however, what `virtualenv` will pick up 
# by default when creating `doc_venv`
python --version
# Python 3.10.4

make html
# ... redacted for brevity ... I can provide entire output if needed
# source ./doc_venv/bin/activate ;\
# set -u ;\
# sphinx-build -M html "." "_build"
# Running Sphinx v1.8.6

# Extension error:
# Could not import extension sphinx.builders.latex (exception: cannot import name 'contextfunction' from 'jinja2' (/home/vise890/code/systemsapproach/book_issue/doc_venv/lib/python3.10/site-packages/jinja2/__init__.py))
# make: *** [Makefile:53: html] Error 2
```

### making it work

So I tried to force python2 for the venv creation:

```Makefile
# Create the virtualenv with all the tools installed
doc_venv:
	virtualenv --python=$(shell which python2) doc_venv ;\
	source ./doc_venv/bin/activate ;\
	pip install livereload ;\
	pip install -r requirements.txt
```
Then tried building, and it seems to all work :tada:

**Comment by llpeterson** [comment]
Thanks for pointing this out. We are in the process of updating the build
environment, which includes upgrading to Python3. I'll try to get the
updates committed sooner rather than later.

Larry

**Comment by vise890** [comment]
Oh I see, well thank you for the quick reply anyway. I got my epub and lots of reading to do now :stuck_out_tongue: 

Let me know if you need a hand with the porting by the way. This is such a great project and I'd love to give something back. I can't guarantee anything, but I can give it a try...

**Comment by llpeterson** [comment]
Thanks! I'm rolling out the updates one book/repo at a time (TCP Congestion
Control and Edge Cloud Operations so far), just in case the changes trigger
some book-specific formatting problem. The main book will probably be last.

Larry

**Comment by vise890** [comment]
Makes sense, best of luck with it all!

**Comment by drbruced12** [comment]
We just rolled out an update to the tools today and (for me and Larry at least) python3 is working fine. Please let us know if you think we can close this issue or if you're still having problems.

**Comment by vise890** [comment]
Oh nice! Worked like a charm for me as well, closing.
