### ISSUE TITLE
Typo In Section 3.3.6

### ISSUE THREAD

**Issue by Innominata88** [SystemsApproach/book#52]
I wanted to address a typo I found in the second paragraph of Section 3.3.6 which reads:

"One simple way to map an IP address into a physical network address is to encode a host’s physical address in the host part of its IP address. For example, a host with physical address 00100001 01001001 (which has the decimal value 33 in the upper byte and 81 in the lower byte) might be given the IP address 128.96.33.81."

I believe there is a typo in the binary representation of the physical address as "01001001" would be 73, but the rest of the sentence indicates this was meant to be 81 (01010001).

![Section_3-3-6_Typo](https://user-images.githubusercontent.com/59786184/194582132-f42a72b9-e60b-4978-be88-7fe4b27fa246.png)

I was unsure of the best place to bring this to your attention, so I apologize if I should not have submitted it here.

**Comment by drbruced12** [comment]
Thank you - you are correct and the error has been around since our first edition! Fixed in commit 5b41d2
