### ISSUE TITLE
Typo in Section 3.2

### ISSUE THREAD

**Issue by elupevg** [SystemsApproach/book#58]
Hello, I found a typo in the sentence:

> But today most networks deploy Ethernet in a point-to-point configuration, with these links interconneted by L2 switches to form a switched Ethernet.

where the word "interconneted" is misspelled.

I hope this is the right place to report it (saw another issue created for a typo), otherwise, sorry for posting it here.

**Comment by drbruced12** [comment]
Good catch - thank you. Not sure how it made it through for this long. Fixed in commit 9011169
