### ISSUE TITLE
fix latency figure label

### ISSUE THREAD

**Issue by mmsaki** [SystemsApproach/book#82]
## [Section 1.5.1-bandwidth-and-latency](https://github.com/SystemsApproach/book/blob/master/foundation/performance.rst#151-bandwidth-and-latency)

- Fix latency chart label for this figure
  - Correct Options
    - Divide link bandwidth by factor of 10
    - Or multiply the object size by factor of 10

<img width="628" alt="SCR-20240824-ejqo" src="https://github.com/user-attachments/assets/1fe52b56-a78e-4f3b-b95b-fb85eb638c41">

**OR** 

<img width="628" alt="SCR-20240824-ejqo-2" src="https://github.com/user-attachments/assets/8c8ab321-93ec-49ad-b3e0-fe2ed2920905">

**Comment by drbruced12** [comment]
I think you have failed to notice that object sizes are in megabytes (MB) while link speeds are in megabits per second (Mbps). So to take the first example, 1MB is 8 Mb, so sending that at 1.5 Mbps takes 5.33 seconds or 5333 milliseconds. So the figures are correct. Perhaps we could stress the different units for object size and link speeds more heavily to avoid confusion.
